### PR TITLE
Mayhem Integration

### PR DESCRIPTION
**Pull request by prateekvishnu**

### CODE REVIEW

**Comment by xansec** [comment]
I'm willing to accept this, but I'm a little concerned about the performance of this target. I tried my hand at a much simpler target here, https://mayhem.forallsecure.com/xansec/wizer/fuzz-wizer/3, and while the generated test cases aren't much higher, it seems to have much better performance overall. I understand you didn't write the fuzz target - but looking at it, I wonder if the complexity of the target keeps us from effectively fuzzing the functions we're interested in...

**Comment by prateekvishnu** [comment]
I can't see the your run.

**Comment by xansec** [comment]
Sorry - here you can see my changes - https://github.com/xansec/wizer
I just made the run public so you should be able to see it now.

**Comment by xansec** [comment]
Awesome, this is much better!

**Pull request merged**
